// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5V-Wd8fP1qUKqcEYNc_lmda8yiIJ36Y',
    appId: '1:484924505004:web:aa1b8f404e5d0759b45809',
    messagingSenderId: '484924505004',
    projectId: 'event-ease-db',
    authDomain: 'event-ease-db.firebaseapp.com',
    storageBucket: 'event-ease-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcAXroxRRhL_49LnJgvsVuhKOxOwZ8b9w',
    appId: '1:484924505004:android:afae5b23dd93bb97b45809',
    messagingSenderId: '484924505004',
    projectId: 'event-ease-db',
    storageBucket: 'event-ease-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC415IebfVTKnyleU0RiH1vQWl_g4hYN8o',
    appId: '1:484924505004:ios:42da3add0bb4d8aab45809',
    messagingSenderId: '484924505004',
    projectId: 'event-ease-db',
    storageBucket: 'event-ease-db.firebasestorage.app',
    iosBundleId: 'com.example.flutterEventEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC415IebfVTKnyleU0RiH1vQWl_g4hYN8o',
    appId: '1:484924505004:ios:42da3add0bb4d8aab45809',
    messagingSenderId: '484924505004',
    projectId: 'event-ease-db',
    storageBucket: 'event-ease-db.firebasestorage.app',
    iosBundleId: 'com.example.flutterEventEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb5V-Wd8fP1qUKqcEYNc_lmda8yiIJ36Y',
    appId: '1:484924505004:web:2b25fc5667373578b45809',
    messagingSenderId: '484924505004',
    projectId: 'event-ease-db',
    authDomain: 'event-ease-db.firebaseapp.com',
    storageBucket: 'event-ease-db.firebasestorage.app',
  );
}
